name: Build and deploy Node.js app to Azure Web App - labourlink

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Display Node.js version
        run: node --version

      - name: Display npm version
        run: npm --version

      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build --if-present
          npm run test -- --passWithNoTests
      
      - name: List files after build
        run: ls -la

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: List files after download
        run: ls -la

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_79AC385E6427440EB2F934CBFC659F75 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_53BD1A60C1EE478F9F1A57267A1CD4A8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EDC7EBCA8C0A4CECB531B590ED9309C5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'labourlink'
          slot-name: 'Production'
          package: .
